version: '3'
 
services:
  my-frontend:
    container_name: my-frontend
    build: ./notes-ui
    # image: dev-lav-frontend:v2
    ports:
      - "6003:3000"
 
  my-backend:
    container_name: my-backend
    build: ./server 
    #image: dev-lav-backend:v2
    environment:
      - APP_ENV=test  
    ports:
      - "6004:4006"
 
 
  my-db:
      build: ./server/database    
     #image: dev-lav-db:latest
      ports:
        - "3306:3306"
