version: '3'
 
services:
  my-frontend:
    build: ./notes-ui
    image: dev-lav-frontend:v2
    ports:
      - "6003:3000"
 
  my-backend:
    build: ./server 
    image: dev-lav-backend:v2
    environment:
      - APP_ENV=test  
    ports:
      - "6004:4006"
 
 
  my-db:
      image: dev-lav-db:latest
      ports:
        - "3306:3306"
